myshop/myshop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from products import views as products_views
from accounts import views as accounts_views
from carts import views as carts_views
from orders import views as orders_views

urlpatterns = [
    url(r'^$',products_views.home,name='home'),
    url(r'^home/$',products_views.home,name='home'),
    url(r'^about/$',products_views.about,name='about'),
    url(r'^contact/$',products_views.contact,name='contact'),

    #url(r'^products/$', products.views.all, name='all'),
    url(r'^products/(?P<slug>[-\w]+)/$',products_views.single, name='single'),
    url(r'^products/(?P<slug>[-\w]+)/$',products_views.subcategory, name='subcategory'),

    url(r'^cart/(?P<id>\d+)/$', carts_views.cart_remove, name='cart_remove'),
    url(r'^cart/(?P<slug>[\w-]+)/$', carts_views.cart_add, name='cart_add'),
    url(r'^cart/$', carts_views.cart, name='cart'),

    url(r'^checkout/$', orders_views.checkout, name='checkout'),
    url(r'^orders/$', orders_views.orders, name='orders'),

    url(r'^login/$',accounts_views.login,name='login'),
    url(r'^logout/$',accounts_views.signout, name='logout'),
    url(r'^register/$',accounts_views.register,name='register'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', accounts_views.activation, name='activation'),
    url(r'^accounts/add_address/$', accounts_views.add_address, name='add_address'),

    
    url(r'^admin/', admin.site.urls),


    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)'''
 

myshop/products/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse

class Category(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	featured = models.BooleanField(default=None)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.title

class Subcategory(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category)
	slug = models.SlugField(unique=True)
	featured = models.BooleanField(default=None)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.title



class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	sub_category = models.ManyToManyField(Subcategory)
	price = models.DecimalField(max_digits=10, decimal_places=1, default=29.99)
	sale_price = models.DecimalField(max_digits=10, decimal_places=1, null=True, blank=True)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title

	class Meta:
		unique_together = ('title', 'slug')

	def get_price(self):
		return self.price

	def get_absolute_url(self):
		return reverse("single", kwargs={"slug": self.slug})

class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to='products/images/',default='products/images/default.jpg')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		return self.product.title

class VariationManager(models.Manager):
	def all(self):
		return super(VariationManager, self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')


VAR_CATEGORIES = (
	('size', 'size'),
	('color', 'color'),
	('package', 'package'),
	)

class Variation(models.Model):
	product = models.ForeignKey(Product)
	category = models.CharField(max_length=120 , choices=VAR_CATEGORIES, default='color')
	title = models.CharField(max_length=120)
	image = models.ForeignKey(ProductImage, null=True, blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=1, null=True, blank=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.title

myshop/templates/about.html
{% extends 'index.html' %}

{% block about %}
<div class="pageTitle">
	<div class="container">
	<h2>About Us</h2>
	</div>
	</div>
	
	 <div class="container">
	 <div class="bodyInner">
			<p>
			Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p><p>
		It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

		 </p><p>
		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
		</p><p>
		The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
		</p><p>
		There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
			</p>
	</div>
	</div>
{% endblock %}	

myshop/templates/contact.html
{% extends 'index.html' %}

{% block contact %}
{% load staticfiles %}
<div class="pageTitle">
	<div class="container">
	<h2>Contact Us</h2>
	</div>
</div>
	
<div class="container" style="background: #ffffff url("{% static 'themes/assets/images/shop.jpg' %}") no-repeat right top;">
	<div class="bodyInner">
		<p>
		&nbsp;
		</p>

		<h4>
		Address &nbsp;&nbsp;: Fashion Textiles
		<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		Near C H colony 
		<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		Vellimadukunnu P O
		<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		Paroppadi
		<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		Calicut-673012
		<br>
		<br>
		Call Us &nbsp;&nbsp;&nbsp;: **********
		<br>
		<br>
		Email Us : fashionworld@gmail.com
		<br>
		</h4>

		<p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		</p><p>&nbsp;
		
		</p>
	</div>
</div>

{% endblock %}
	
	

myshop/templates/form.html
{% extends 'index.html' %}

{% block form %}


<div>

<form method="POST" action=" " >{% csrf_token %}
	{{form.as_p}}
	<input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' class='btn btn-default' />

</form>

</div>

{% endblock %}

myshop/templates/home.html
{% extends 'index.html'%}

{% block base %}
{% load staticfiles %}

<div class="container marketing">
	<h2 class="itemsTitle">LATEST COLLECTION</h2>
    <!-- Three columns of text below the carousel -->
    <div class="row">
    {% for product in products %}
		<div class="col-lg-4">
        {% for productimage in product.productimage %}
          	<a href="{{ product.get_absolute_url }}"><img class="img-circle" src="{{ productimage.image.url }}" alt="{{product.title}}" style="width:170px; height:250px;"></a>
        {% endfor %}
          	<h5>{{product.title}}</h5>
          	<p>{{product.description }}</p>
          	<p>
          	<form class='form' method='POST' action="{% url 'cart_add' product.slug %}"> {% csrf_token %}
			<input class='btn btn-default' type='submit' value='&#8377; {{product.price}} Add to cart &raquo;'/></form>
			</p>
        </div><!-- /.col-lg-4 -->
    {% endfor %}
    </div><!-- /.row -->
</div>
	
<div class="introSection">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="cntr">We are launching complete fashion dress's online store with lowest price. <br>special collection from &#8377;250- &#8377;2500</h1>
			</div>
		</div>
	</div>
</div>

{% for category in categorys %}
<div class="container marketing">
    <h2 class="itemsTitle">{{category.title}}</h2>
	<div id="myCarousel1" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
	    <div class="carousel-inner">
	    {% if category.subcategory_set.all %}
		    {% for subcategory in category.subcategory_set.all %}
		    	<div class="item {% if forloop.first %} active {% endif %}">
			    <h4>{{subcategory.title}}</h4>
			        <div class="row">
			        {% if subcategory.product_set.all %}
				        {% for product in subcategory.product_set.all %}
				        	<div class="col-lg-4">
				        	{% if product.productimage_set.all %}
				        		{% for productimage in product.productimage_set.all %}
				        			<a href="{{ product.get_absolute_url }}"><img src="{{ productimage.image.url }}" alt="{{product.title}}" style="width:150px; height:250px;"/></a>	
				        		{% endfor %}
				        	{% endif %}
				          		<h5>{{product.title}}</h5>
				          		<p>
				          		<form class='form' method='POST' action="{% url 'cart_add' product.slug %}"> {% csrf_token %}
			 	 				<input class='btn btn-default' type='submit' value='Add to cart &raquo;'/></form>
			 	 				</p>
				        	</div><!-- /.col-lg-4 -->
						{% endfor %}
					{% endif %}
			      	</div><!-- /.row -->
		        </div><!--item -->
	        {% endfor %}
	    {% endif %}
	    </div>
	<a class="left carousel-control" href="#myCarousel1" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	<a class="right carousel-control" href="#myCarousel1" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	</div><!-- /.carousel -->
</div>
{% endfor %}

<div class="mainTitle">
<div class="container ">
<h4>FEATURED PRODUCTS</h4>
</div>
</div>

<div class="highlightSection" >
<div class="container">
	<div class="row">
		{% for pdt in p %}
			{% for image in pdt.productimage %}
				<div class="col-lg-4">
					<div class="media">
						<a href="{{ pdt.get_absolute_url }}"><img src="{{ image.image.url }}" alt="{{product.title}}"
						style="width:150px; height:250px;"> </a>
						<h4 class="media-heading text-primary-theme">{{pdt.title}}</h4>
						<p>{{pdt.description}}</p>
					</div>
				</div>
			{% endfor %}
		{% endfor %}
	</div>
</div>
</div>




{% endblock %}

myshop/templates/index.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'themes/assets/ico/favicon.ico' %}">
    <title>myshop</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'themes/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'themes/dist/css/bootstrap-submenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'themes/assets/css/carousel.css' %}" rel="stylesheet">
    <style >
    	{% block styles %} {% endblock %}
    </style>
</head>

<body>  
    <!-- NAVBAR HERE================================================== -->
    {% include 'navbar.html' %}
    
    <!-- Carousel
    ================================================== -->
    <div id="mainCarousel">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <script
			src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
			</script>
			<script>
			var myCenter=new google.maps.LatLng(11.2857255, 75.8154105);
			var marker;
			function initialize()
			{
			var mapProp = {
			  center:myCenter,
			  zoom:15,
			  mapTypeId:google.maps.MapTypeId.ROADMAP
			  };
			var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
			marker=new google.maps.Marker({
			  position:myCenter,
			 // icon:'themes/assets/images/nepali-momo.png',
			  animation:google.maps.Animation.BOUNCE
			  });

			marker.setMap(map);

			// Info open
			var infowindow = new google.maps.InfoWindow({
			  content:"Hello World!"
			  });

			google.maps.event.addListener(marker, 'click', function() {
			  infowindow.open(map,marker);
			  });
			}
			google.maps.event.addDomListener(window, 'load', initialize);
			</script>
			<div id="googleMap" style="height:450px;"></div>
			  <div class="container">
				<div class="carousel-caption">
				  <a class="btn btn-lg btn-default" href="#" role="button" style="font-size:2em">Order Online Now &raquo;</a>
				</div>
			  </div>
			</div>
		  </div>
		</div><!-- /.carousel -->
	</div>

	<div class="mainTitle">
	<div class="container">
	<h1>Fashion World</h1>
	<p>
	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy 
	</p>
	</div>
	</div>
	
	<div class="container">
    {% if messages %}
        {% for message in messages %}
        	<div class='alert {% if "success" in message.tags %}alert-success{% elif "warning" in message.tags%}alert-warning{% elif "error" in message.tags %}alert-danger{% endif %} alert-dismissible' role='alert'>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            	{% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
        {% endfor %}
    {% endif %}
    

    {% block base %}{% endblock %}
	{% block about %} {% endblock %}
	{% block contact %} {% endblock %}
	{% block form %} {% endblock %}
	{% block subcategory %} {% endblock %}
	{% block single %} {% endblock %}
	{% block cart %} {% endblock %}
	{% block content %} {% endblock %}

    </div>
	 
	
	      
  
	<div class="introSection">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
				<h3>Our Info</h3>
				<p>About Us<br>
				Contact Us<br>
				Privacy Policy<br>
				Terms and Conditions<br>
				Support Center<br>
				</p>
				</div>
			
				<div class="col-lg-4">
				<h3>Customer Service</h3>
				<p>
				15 days return<br>
				cash on delivery<br>
				free shipping<br>
				</p>
				
				</div>
			
				<div class="col-lg-4">
				<h3>Find Us On</h3>
				<p>Facebook<br>
				blog<br>
				</p>
				</div>

			</div>
		</div>
	</div>


    <div class="container marketing">
    <div id="myCarousel4" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
    <div class="carousel-inner">

    <div class="item active">
    <div class="row featurette">
        <div class="col-md-7">
	        <h2 class="featurette-heading">Mens Clothing <span class="text-muted">Lucky Size Store</span></h2>
	        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
	    <div class="col-md-5">
	        <img src="{% static 'themes/assets/images/slide1.jpg' %}" alt="Fish and Chips">
	    </div>
    </div>
    </div>
 
	<div class="item">
    <div class="row featurette">
        <div class="col-md-5">
        	<img src="{% static 'themes/assets/images/slide2.jpg' %}" alt="Generic placeholder image">
        </div>
        <div class="col-md-7">
	        <h2 class="featurette-heading">Womens Party Wear<span class="text-muted">Designer Collection</span></h2>
	        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
    </div>
    </div>

	<div class="item">
    <div class="row featurette">
        <div class="col-md-7">
        	<h2 class="featurette-heading">Kid's Clothing <span class="text-muted"> Discount Sale</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
		  	<img class="img-circle" src="{% static 'themes/assets/images/slide3.jpg' %}" alt="Generic placeholder image">
        </div>
    </div>
    </div>

	</div>
    </div><!-- /.carousel -->	  
    </div><!-- /.container -->
    <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
		<div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
		</div>
      </footer>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>
	$(document).ready(function(){
		{% block jquery %}{% endblock%}
	});
	</script>

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'themes/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'themes/assets/js/holder.js' %}"></script>

  </body>
</html>

myshop/templates/navbar.html
<!-- Static navbar -->
<div class="navbar-wrapper">
<div class="container">
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home/">Fashion World</a>
    </div>

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class= "active" class="{% ifequal request.path '/home/' %} active {% endifequal %}" ><a href="/home/">Home</a></li>
            <li class="{% ifequal request.path '/about/'%} active {% endifequal %}"><a href="/about/">About Us</a></li>
            <li class="{% ifequal request.path '/contact/'%} active {% endifequal %}"><a href="/contact/">Contact</a></li>

			<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">products<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    {% for category in categorys %}
                        <li class="dropdown-submenu"><a class="test"  tabindex="-1" href=# >{{category.title}}</a>
                            <ul class="dropdown-menu">
                            {% if category.subcategory_set.all %}
                                {% for subcategory in category.subcategory_set.all %}
                                    <li><a tabindex="-1"  href="{% url 'subcategory' subcategory.slug %}">
                                    {{subcategory.title}}</a></li>
                                    <li class="divider"></li>
                                {% endfor %}
                            {% endif %}
                            </ul>
                        </li>
                        <li class="divider"></li>
                    {% endfor %}
                </ul>
            </li>

            {% if request.user.is_authenticated %}
                <li class="{% ifequal request.path '/logout/' %} active {% endifequal %}">
                    <a href="/cart/"><span class="glyphicon glyphicon-shopping-cart"></span> My Cart</a></li>
                <li class="{% ifequal request.path '/logout/' %} active {% endifequal %}">
                    <a href="/logout/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            {% else %}
                <li class="{% ifequal request.path '/register/'%} active {% endifequal %}">
                    <a href="/register/"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li class="{% ifequal request.path '/login/' %} active {% endifequal %}">
                    <a href="/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}

        </ul>
    </div>
</div>
</div>
</div>
</div>